version: "3.9"
services:
  db:
    # コンテナ名の指定
    container_name: subscription_db
    # イメージの指定
    image: postgres:14
    # データの永続化
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # 環境変数の指定
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  web:
    # コンテナ名の指定
    container_name: subscription_app
    # Dockerfile のあるディレクトリのパスを指定
    build: .
    # デフォルトのコマンド指定
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # データの永続化
    volumes:
      - .:/subscription_app_back
    # ポートの指定
    ports:
      - "3000:3000"
    # 依存関係の指定
    depends_on:
      - db
  mock-server:
    image: stoplight/prism:3
    container_name: "swagger-api"
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 /openapi.yml
    volumes:
      - ./docs/openapi.yml:/openapi.yml
