name: Run rspec

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# permissions:

jobs:
  rspec:
    runs-on: ubuntu-latest
    # timeout-minutes: 10
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        # options: >-
        #   --mount type=tmpfs,destination=/var/lib/postgresql/data
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v3
        with:
        ruby-version: 3.1.2
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
          bundle exec rails db:seed RAILS_ENV=test

      - name: Run rspec
        run: bundle exec rspec